"""Add last_tip_date to User

Revision ID: b8de347e4fbf
Revises: eb9bd05a2a8f
Create Date: 2026-05-27 01:48:54.309122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8de347e4fbf'
down_revision: Union[str, Sequence[str], None] = 'eb9bd05a2a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_tip_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_tip_date')
    # ### end Alembic commands ###
